import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1f",
        "surface-bright": "#f7f9fd",
        "on-surface-variant": "#444748",
        "on-tertiary-container": "#7d8497",
        "surface-container-highest": "#e0e2e6",
        "primary-fixed": "#e5e2e1",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f5",
        "surface-container-high": "#e6e8ec",
        "on-surface": "#191c1f",
        "on-secondary-fixed": "#151c27",
        "primary-fixed-dim": "#c9c6c5",
        "surface-variant": "#e0e2e6",
        "on-secondary-fixed-variant": "#404754",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#474646",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c4c7c7",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#858383",
        "surface-dim": "#d8dade",
        "on-tertiary-fixed-variant": "#404758",
        "secondary-fixed": "#dce2f3",
        "inverse-surface": "#2d3134",
        "on-primary": "#ffffff",
        "tertiary": "#000000",
        "background": "#f7f9fd",
        "outline": "#747878",
        "surface": "#f7f9fd",
        "on-primary-fixed": "#1c1b1b",
        "tertiary-fixed-dim": "#c0c6db",
        "tertiary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#c0c7d6",
        "primary-container": "#1c1b1b",
        "primary": "#000000",
        "on-secondary-container": "#5e6572",
        "inverse-primary": "#c9c6c5",
        "tertiary-container": "#141b2b",
        "on-secondary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "surface-container-low": "#f2f4f8",
        "secondary-container": "#dce2f3",
        "surface-container": "#eceef2",
        "on-tertiary-fixed": "#141b2b",
        "secondary": "#585f6c",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "card-padding": "20px",
        "container-max-width": "1200px",
        "section-gap": "32px",
        "element-gap": "16px",
        base: "8px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "label-medium": ["Inter"],
        h1: ["Inter"],
        "body-sm": ["Inter"],
        "data-display": ["Inter"],
        h2: ["Inter"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-medium": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        h1: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-display": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" }],
        h2: ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;